start-at-login = true
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.top = 8
outer.bottom = 8
outer.left = 8
outer.right = 24
[mode.main.binding]
alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"
alt-shift-h = "move left"
alt-shift-j = "move down"
alt-shift-k = "move up"
alt-shift-l = "move right"
alt-1 = "workspace 1"
alt-2 = "workspace 2"
alt-3 = "workspace 3"
alt-4 = "workspace 4"
alt-5 = "workspace 5"
alt-6 = "workspace 6"
alt-7 = "workspace 7"
alt-8 = "workspace 8"
alt-9 = "workspace 9"
alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-4 = "move-node-to-workspace 4"
alt-shift-5 = "move-node-to-workspace 5"
alt-shift-6 = "move-node-to-workspace 6"
alt-shift-7 = "move-node-to-workspace 7"
alt-shift-8 = "move-node-to-workspace 8"
alt-shift-9 = "move-node-to-workspace 9"
alt-enter = "exec-and-forget open -na 'Ghostty'"
alt-b = "layout horizontal"
alt-slash = "layout vertical"
alt-comma = "layout accordion"
alt-f = "fullscreen"
alt-space = "mode apps"
alt-x = "exec-and-forget sketchybar --trigger aerospace_workspace_change"
[mode.apps.binding]
w = "exec-and-forget open -na 'WezTerm'"
t = "exec-and-forget open -na 'Ghostty'"
c = "exec-and-forget open -na 'Visual Studio Code'"
s = "exec-and-forget open -a 'Safari'"
o = "exec-and-forget open -a 'Obsidian'"
r = "exec-and-forget open -a 'Raycast'"
m = "exec-and-forget open -a 'Maccy'"
q = "mode main"
[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1
9 = 1
