# AeroSpace Configuration
# Unified configuration with workspace automation support

start-at-login = true

# Enable normalization for better container handling
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Default layouts
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
accordion-padding = 30

# Startup commands - initialize borders and sketchybar
after-startup-command = [
  'exec-and-forget borders active_color=0xff89b4fa inactive_color=0xff45475a width=5.0',
  'exec-and-forget sketchybar --trigger aerospace_workspace_change'
]

# Gaps configuration
[gaps]
inner.horizontal = 8
inner.vertical = 8
outer.top = 8
outer.bottom = 8
outer.left = 8
outer.right = 24

# Window detection rules - automatically place apps
[[on-window-detected]]
if.app-id = 'com.mitchellh.ghostty'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
check-further-callbacks = true

[[on-window-detected]]
if.app-id = 'com.apple.Safari'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 6'

# Main mode keybindings
[mode.main.binding]
# Focus windows (vim-style)
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Move windows
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Workspace switching
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'

# Move window to workspace
alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'

# Quick terminal
alt-enter = 'exec-and-forget open -na "Ghostty"'

# Layout controls
alt-b = 'layout h_tiles'
alt-v = 'layout v_tiles'
alt-slash = 'layout v_tiles h_tiles'
alt-comma = 'layout h_accordion v_accordion'
alt-f = 'fullscreen'

# Mode switches
alt-r = 'mode resize'
alt-space = 'mode apps'
alt-i = 'mode layout-init'

# Utility commands
alt-x = 'exec-and-forget sketchybar --trigger aerospace_workspace_change'
alt-shift-s = 'exec-and-forget screencapture -i -c'

# Apps mode - quick application launcher
[mode.apps.binding]
w = ['exec-and-forget open -na "WezTerm"', 'mode main']
t = ['exec-and-forget open -na "Ghostty"', 'mode main']
c = ['exec-and-forget open -na "Visual Studio Code"', 'mode main']
s = ['exec-and-forget open -a "Safari"', 'mode main']
b = ['exec-and-forget open -na "Google Chrome"', 'mode main']
o = ['exec-and-forget open -a "Obsidian"', 'mode main']
r = ['exec-and-forget open -a "Raycast"', 'mode main']
m = ['exec-and-forget open -a "Maccy"', 'mode main']
q = 'mode main'
esc = 'mode main'

# Resize mode for precise window sizing
[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
shift-h = 'resize width -10'
shift-j = 'resize height +10'
shift-k = 'resize height -10'
shift-l = 'resize width +10'
minus = 'resize smart -50'
equal = 'resize smart +50'
q = 'mode main'
esc = 'mode main'
enter = 'mode main'

# Layout initialization mode - trigger workspace setup scripts
[mode.layout-init.binding]
1 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_1.sh', 'mode main']
2 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_2.sh', 'mode main']
3 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_3.sh', 'mode main']
4 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_4.sh', 'mode main']
5 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_5.sh', 'mode main']
6 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_6.sh', 'mode main']
7 = ['exec-and-forget ~/.config/aerospace/scripts/init_workspace_7.sh', 'mode main']
a = ['exec-and-forget ~/.config/aerospace/scripts/init_all_workspaces.sh', 'mode main']
r = ['exec-and-forget ~/.config/aerospace/scripts/reset_workspace.sh', 'mode main']
q = 'mode main'
esc = 'mode main'

# Workspace to monitor assignment (all to main monitor)
[workspace-to-monitor-force-assignment]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
6 = 1
7 = 1
8 = 1
9 = 1
