repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.10.0.1
  hooks:
    - id: shellcheck
- repo: https://github.com/scop/pre-commit-shfmt
  rev: v3.10.0-1
  hooks:
    - id: shfmt
      args: ["-i", "2", "-s", "-ci"]
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.22.1
  hooks:
    - id: gitleaks
      name: gitleaks (repo scan)
      args: ["--redact"]

# regenerate DIRECTORY_CONTEXT.md on every commit
- repo: local
  hooks:
    - id: regenerate-directory-context
      name: Regenerate DIRECTORY_CONTEXT.md
      entry: bash scripts/generate_context.sh
      language: system
      pass_filenames: false
