export OPENROUTER_API_KEY="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"


# Added by Windsurf
export PATH="/Users/p8/.codeium/windsurf/bin:$PATH"

# Development environment setup
export PATH="/opt/homebrew/bin:/usr/local/bin:$HOME/.local/bin:$PATH"
export EDITOR=vim
export VISUAL=vim

# Load completion system
autoload -Uz compinit
compinit

eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
bindkey -v
export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
eval "$(fzf --zsh)"
eval "$(carapace _carapace zsh)"
eval "$(direnv hook zsh)"
eval "$(mise activate zsh)"
eval "$(atuin init zsh)"
alias ls='eza -lah --group-directories-first --icons'
alias cat='bat'
alias grep='rg'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
